[package]
name = "kum-io-client"
version = "0.0.0"
authors = ["Blay"]
license = "GPL-3.0-only"
repository = "https://github.com/Blayung/kum.io"
edition = "2021"

[dependencies]
sdl2 = { version = "0.32.2", default-features = false }
